In [2]:
import pandas as pd

## Pandas is a popular open-source Python library used for data analysis and data manipulation. It’s especially useful when working with structured data like tables

# What Pandas is used for
Cleaning messy data (missing values, duplicates, formatting)
Analyzing datasets (statistics, filtering, grouping)
Reading/writing data (CSV, Excel, SQL, JSON, etc.)
Time series analysis (dates, trends)
Data transformation (merging, reshaping)

## Core concepts
* Series → a single column of data (like a list with labels)
* DataFrame → a table of rows and columns (most commonly used)

In [3]:
covid_df = pd.read_csv('italy-covid-daywise.csv')

In [4]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

Data from the file is read and stored in a DataFrame object - one of the core data structures in Pandas for storing and working with tabular data . We typically use the _df suffix in the variable names for dataframes.

In [5]:
type(covid_df)

pandas.DataFrame

In [7]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [8]:
covid_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    str
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), str(1)
memory usage: 7.9 KB

In [9]:
covid_df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

* It appears that each column contains values of a specific data type . For the numeric columns , you can view the some statistical information like mean,standard deviation , minimum/maximum values and number of non-empty values using the .describe() method .

* The columns property contains the list of columns within the data frame.

In [11]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

* You can also retrieve the number of rows and columns in the frame using the .shape property

In [12]:
covid_df.shape

(248, 4)