In [2]:
import pandas as pd

## Pandas is a popular open-source Python library used for data analysis and data manipulation. It’s especially useful when working with structured data like tables

# What Pandas is used for
Cleaning messy data (missing values, duplicates, formatting)
Analyzing datasets (statistics, filtering, grouping)
Reading/writing data (CSV, Excel, SQL, JSON, etc.)
Time series analysis (dates, trends)
Data transformation (merging, reshaping)

## Core concepts
* Series → a single column of data (like a list with labels)
* DataFrame → a table of rows and columns (most commonly used)

In [3]:
covid_df = pd.read_csv('italy-covid-daywise.csv')

In [4]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

Data from the file is read and stored in a DataFrame object - one of the core data structures in Pandas for storing and working with tabular data . We typically use the _df suffix in the variable names for dataframes.

In [5]:
type(covid_df)

pandas.DataFrame

In [6]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [7]:
covid_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 248 entries, 0 to 247
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        248 non-null    str
 1   new_cases   248 non-null    float64
 2   new_deaths  248 non-null    float64
 3   new_tests   135 non-null    float64
dtypes: float64(3), str(1)
memory usage: 7.9 KB

In [8]:
covid_df.describe()

         new_cases  new_deaths     new_tests
count   248.000000  248.000000    135.000000
mean   1094.818548  143.133065  31699.674074
std    1554.508002  227.105538  11622.209757
min    -148.000000  -31.000000   7841.000000
25%     123.000000    3.000000  25259.000000
50%     342.000000   17.000000  29545.000000
75%    1371.750000  175.250000  37711.000000
max    6557.000000  971.000000  95273.000000

* It appears that each column contains values of a specific data type . For the numeric columns , you can view the some statistical information like mean,standard deviation , minimum/maximum values and number of non-empty values using the .describe() method .

* The columns property contains the list of columns within the data frame.

In [9]:
covid_df.columns

Index(['date', 'new_cases', 'new_deaths', 'new_tests'], dtype='str')

* You can also retrieve the number of rows and columns in the frame using the .shape property

In [10]:
covid_df.shape

(248, 4)

In [11]:
covid_df.shape[0] # returns the number of rows in dataframe

248

In [12]:
covid_df.shape[1] # return the number of columns in dataframe

4

* Here's a summary of the functions and methods we've looked at so far :

* pd.read_csv - Reads data from a CSV file into a Pandas DataFrame object

* .info() - View basic information about rows , columns and data types 

* .describe() - view statistical information about numeric columns 

* .shape - Get the number of rows and columns as a tuple

In [13]:
covid_df['new_cases']

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

Each column is represented using a data structure called series , Which is essentially a numpy array with a some extra methods and properties.

In [14]:
type(covid_df['new_cases'])

pandas.Series

* Just like a arrry you can retrive a specific value with a series using the indexing notation [].

In [15]:
covid_df['new_cases'][246]

np.float64(975.0)

In [16]:
covid_df['new_cases'][240]

np.float64(1366.0)

* Pandas also provides the   .at  method to directly retrive at a specific row and column.

In [17]:
covid_df.at[246,'new_cases']

np.float64(975.0)

In [18]:
covid_df.at[240,'new_cases']

np.float64(1366.0)

In [19]:
covid_df.new_cases

0         0.0
1         0.0
2         0.0
3         0.0
4         0.0
        ...
243    1444.0
244    1365.0
245     996.0
246     975.0
247    1326.0
Name: new_cases, Length: 248, dtype: float64

* Further , you can also pass a list of columns within the indexing notation []  to access a subset of the data frame with just the given columns .

In [20]:
cases_df = covid_df[['date','new_cases']]
cases_df

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
243  2020-08-30     1444.0
244  2020-08-31     1365.0
245  2020-09-01      996.0
246  2020-09-02      975.0
247  2020-09-03     1326.0

[248 rows x 2 columns]

Note, however, that the new data frame cases_df is simply a "view" of the original data frame covid_df i.e. they both point to the same data in the computer's memory, and changing any values inside one of them will also change the respective values in the other. Sharing data between data frames makes data manipulation in Pandas blazing fast, and you needn't worry about the overhead of copying thousands or millions of rows every time you want to crate a new data frame by operating on an existing one.

Sometimes you might need a full copy of the data frame, in which case you can use the copy method.

In [21]:
covid_df_copy = covid_df.copy()

In [22]:
covid_df_copy

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

The data within covid_df_copy is completely separate from covid_df ,and changing values inside one of them will be not affect the other .

In [23]:
covid_df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

* To access a specific row of data pandas provides the   .loc  method.

In [24]:
covid_df.loc[243]

date          2020-08-30
new_cases         1444.0
new_deaths           1.0
new_tests        53541.0
Name: 243, dtype: object

In [25]:
covid_df.loc[0:4]

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [26]:
covid_df.loc[:, ['date', 'new_cases']]

           date  new_cases
0    2019-12-31        0.0
1    2020-01-01        0.0
2    2020-01-02        0.0
3    2020-01-03        0.0
4    2020-01-04        0.0
..          ...        ...
243  2020-08-30     1444.0
244  2020-08-31     1365.0
245  2020-09-01      996.0
246  2020-09-02      975.0
247  2020-09-03     1326.0

[248 rows x 2 columns]

In [27]:
covid_df.loc[covid_df['new_cases'] > 100]

           date  new_cases  new_deaths  new_tests
59   2020-02-28      250.0         5.0        NaN
60   2020-02-29      238.0         4.0        NaN
61   2020-03-01      240.0         8.0        NaN
62   2020-03-02      561.0         6.0        NaN
63   2020-03-03      347.0        17.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[188 rows x 4 columns]

* .iloc[] is used to select data by position (index number) — not by labels.

In [28]:
covid_df.iloc[246, 2]

np.float64(8.0)

In [29]:
covid_df.iloc[246]

date          2020-09-02
new_cases          975.0
new_deaths           8.0
new_tests            NaN
Name: 246, dtype: object

In [30]:
covid_df.iloc[0:5]

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [31]:
covid_df.iloc[:, [0, 2]]

           date  new_deaths
0    2019-12-31         0.0
1    2020-01-01         0.0
2    2020-01-02         0.0
3    2020-01-03         0.0
4    2020-01-04         0.0
..          ...         ...
243  2020-08-30         1.0
244  2020-08-31         4.0
245  2020-09-01         6.0
246  2020-09-02         8.0
247  2020-09-03         6.0

[248 rows x 2 columns]

In [32]:
covid_df.iloc[0:5, 0:2]

         date  new_cases
0  2019-12-31        0.0
1  2020-01-01        0.0
2  2020-01-02        0.0
3  2020-01-03        0.0
4  2020-01-04        0.0

In [33]:
type(covid_df.loc[243])

pandas.Series

* To view the first or last few rows of data , we can use the  .head and  .tail  methods

In [34]:
covid_df.head(5)

         date  new_cases  new_deaths  new_tests
0  2019-12-31        0.0         0.0        NaN
1  2020-01-01        0.0         0.0        NaN
2  2020-01-02        0.0         0.0        NaN
3  2020-01-03        0.0         0.0        NaN
4  2020-01-04        0.0         0.0        NaN

In [35]:
covid_df.tail(5)

           date  new_cases  new_deaths  new_tests
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

* We can find the index that doesn't contain a NaN value using first_valid_index method of a series .

In [36]:
covid_df.new_tests.first_valid_index()

111

In [37]:
covid_df.loc[108:113]

           date  new_cases  new_deaths  new_tests
108  2020-04-17     3786.0       525.0        NaN
109  2020-04-18     3493.0       575.0        NaN
110  2020-04-19     3491.0       480.0        NaN
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0

* The .sample method can be used to retrieve a random sample of rows from the data frame.

In [38]:
covid_df.sample(10)

           date  new_cases  new_deaths  new_tests
67   2020-03-07      778.0        49.0        NaN
121  2020-04-30     2086.0       323.0    41441.0
87   2020-03-27     6153.0       660.0        NaN
175  2020-06-23      221.0        23.0    23225.0
43   2020-02-12        0.0         0.0        NaN
19   2020-01-19        0.0         0.0        NaN
49   2020-02-18        0.0         0.0        NaN
95   2020-04-04     4585.0       764.0        NaN
219  2020-08-06      384.0        10.0    32169.0
170  2020-06-18      328.0        43.0    32921.0

In [39]:
covid_df.sample(frac=0.1) # 👉 Returns 10% of the dataset

           date  new_cases  new_deaths  new_tests
130  2020-05-09     1327.0       243.0    36091.0
92   2020-04-01     4053.0       839.0        NaN
209  2020-07-27      254.0         5.0    19374.0
171  2020-06-19      331.0        66.0    28570.0
54   2020-02-23       62.0         2.0        NaN
105  2020-04-14     3153.0       564.0        NaN
86   2020-03-26     5210.0       685.0        NaN
47   2020-02-16        0.0         0.0        NaN
149  2020-05-28      584.0       117.0    39838.0
106  2020-04-15     2972.0       604.0        NaN
30   2020-01-30        0.0         0.0        NaN
48   2020-02-17        0.0         0.0        NaN
27   2020-01-27        0.0         0.0        NaN
87   2020-03-27     6153.0       660.0        NaN
28   2020-01-28        0.0         0.0        NaN
182  2020-06-30      126.0         6.0    28471.0
183  2020-07-01      142.0        23.0    29325.0
109  2020-04-18     3493.0       575.0        NaN
25   2020-01-25        0.0         0.0        NaN
100  2020-04-09     3836.0       540.0        NaN
74   2020-03-14     2547.0       252.0        NaN
213  2020-07-31      382.0         3.0    29686.0
175  2020-06-23      221.0        23.0    23225.0
72   2020-03-12     2313.0       196.0        NaN
75   2020-03-15     3497.0       173.0        NaN

Notice that even though we have taken a random sample , the original index of each row has been preserved. This is an important an useful property of data frames - each row of data has an index associated with it.

* .head() , .tail(), .sample , .loc methods  we learn

## Anylyzing Data from data frame

Q . What is the total number of reported cases and deaths related to covid-19 in Italy ? 

Similar to NumPy arrays , Pandas series supports the sum  method to answer these questions.

In [40]:
total_cases = covid_df.new_cases.sum()
total_deaths = covid_df.new_deaths.sum()

In [41]:
print(f'The number of reported cases in {total_cases} and the number of deaths is {total_deaths} ')

The number of reported cases in 271515.0 and the number of deaths is 35497.0

Q : What is THe overall deaths rate (ratio of reported deats to reported cases)?

In [42]:
death_rate = covid_df.new_deaths.sum()/covid_df.new_cases.sum()

In [43]:
print("THe overall reported death rate in italy is {:.2f}%.".format(death_rate))

THe overall reported death rate in italy is 0.13%.

Q : What is the overall number of tests conducted ? A total of 935310 tests were conducted before daily test numbers were being reported .


we can check the first non-NaN index using first_valid_index

In [44]:
initial_tests = 935310

total_tests = initial_tests + covid_df.new_tests.sum()

In [45]:
total_tests

np.float64(5214766.0)

Q : What fraction of test returned a positive result ?

In [46]:
positive_rate = total_cases / total_tests

In [47]:
print('{:.2f}%  of tests in Italy led to a positive diagnosis.'.format(positive_rate))

0.05%  of tests in Italy led to a positive diagnosis.

## Querying and Sorting rows 

let's say we want only want to look at the days which had more than 1000 reported cases . We can use a boolean expression to check which rows satisfy this criterion.

In [48]:
high_new_cases = covid_df.new_cases > 1000

In [49]:
high_new_cases

0      False
1      False
2      False
3      False
4      False
       ...
243     True
244     True
245    False
246    False
247     True
Name: new_cases, Length: 248, dtype: bool

In [50]:
high_new_cases

0      False
1      False
2      False
3      False
4      False
       ...
243     True
244     True
245    False
246    False
247     True
Name: new_cases, Length: 248, dtype: bool

The boolean expression returns a series containing True and False boolean values. This series can be used to filter our just those rows where the value in the series is True . The result is data frame with a subset of rows from the original.

In [51]:
covid_df[high_new_cases]

           date  new_cases  new_deaths  new_tests
68   2020-03-08     1247.0        36.0        NaN
69   2020-03-09     1492.0       133.0        NaN
70   2020-03-10     1797.0        98.0        NaN
72   2020-03-12     2313.0       196.0        NaN
73   2020-03-13     2651.0       189.0        NaN
..          ...        ...         ...        ...
241  2020-08-28     1409.0         5.0    65135.0
242  2020-08-29     1460.0         9.0    64294.0
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
247  2020-09-03     1326.0         6.0        NaN

[72 rows x 4 columns]

The data frame contains 72 rows , but only the first 5 and last 5 rows are displayed by default with Jupyter , for brevity . To views , all the rows , we can modify some display options .

In [ ]:
from IPython.display import display 
with pd.option_context('display.max_rows',100):
    display(covid_df[covid_df.new_cases > 1000])

we can also formulate more complex queries that involve multiple columns . As an example , let's try to determine the days when the ratio of cases of cases reported to tests conducted  is higher than the overall positive_rate.

In [53]:
positive_rate

np.float64(0.05206657403227681)

In [54]:
high_ratio_df = covid_df[covid_df.new_cases / covid_df.new_tests > positive_rate]

In [55]:
high_ratio_df

           date  new_cases  new_deaths  new_tests
111  2020-04-20     3047.0       433.0     7841.0
112  2020-04-21     2256.0       454.0    28095.0
113  2020-04-22     2729.0       534.0    44248.0
114  2020-04-23     3370.0       437.0    37083.0
116  2020-04-25     3021.0       420.0    38676.0
117  2020-04-26     2357.0       415.0    24113.0
118  2020-04-27     2324.0       260.0    26678.0
120  2020-04-29     2091.0       382.0    38589.0
123  2020-05-02     1965.0       269.0    31231.0
124  2020-05-03     1900.0       474.0    27047.0
125  2020-05-04     1389.0       174.0    22999.0
128  2020-05-07     1444.0       369.0    13665.0

Performing operations on multiple columns results in a new series

In [56]:
covid_df.new_cases / covid_df.new_tests

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
         ...
243    0.026970
244    0.032055
245    0.018311
246         NaN
247         NaN
Length: 248, dtype: float64

Further , we can use this series to add a new column to the data frame.

In [57]:
covid_df['positive_rate'] = covid_df.new_cases / covid_df.new_tests

In [58]:
covid_df

           date  new_cases  new_deaths  new_tests  positive_rate
0    2019-12-31        0.0         0.0        NaN            NaN
1    2020-01-01        0.0         0.0        NaN            NaN
2    2020-01-02        0.0         0.0        NaN            NaN
3    2020-01-03        0.0         0.0        NaN            NaN
4    2020-01-04        0.0         0.0        NaN            NaN
..          ...        ...         ...        ...            ...
243  2020-08-30     1444.0         1.0    53541.0       0.026970
244  2020-08-31     1365.0         4.0    42583.0       0.032055
245  2020-09-01      996.0         6.0    54395.0       0.018311
246  2020-09-02      975.0         8.0        NaN            NaN
247  2020-09-03     1326.0         6.0        NaN            NaN

[248 rows x 5 columns]

Here is the exact text from the file "Screenshot 2026-05-12 220531.png":

Keep in mind however, sometimes it takes a few days to get the results for a test, so we can't really compare the number of new cases with the number of tests conducted on the same day. Any inference based on this positive_rate column is likely to be incorrect. It's important to watch out for subtle relationships like these which are often not conveyed within the CSV file and require some external context. It's always a good idea to read through the documentation provided with the dataset or ask for more information.  

For now, let's remove the positive_rate column using the drop method.

In [59]:
covid_df.drop(columns=['positive_rate'],inplace=True)

Can you figure out what the inplace argument is used for?  

The rows can also be sorted by a specific column using .sort_values . Let's sort to identify the days with the highest number of cases, then chain it with the head method to get the 10 days with the most cases.